readUCIdata=read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
readUCIdata$Date=as.Date(readUCIdata$Date,"%d/%m/%Y")
finaldt=subset(readUCIdata,Date>=as.Date("2007-02-01") & Date <=as.Date("2007-02-02"))
png(filename="plot1.png",width=480,height=480, units="px")
hist(finaldt$Global_active_power,col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()